from django.urls import path

from .views import (
    ConsumerManagerApproveDemandView,
    ConsumerManagerApproveGeneratorScheduleView,
    ConsumerManagerDemandEntrySummaryView,
    ConsumerManagerOverallDemandSlotsView,
    ConsumerManagerPlantDemandSlotsView,
    ConsumerManagerDemandWeekView,
    ConsumerManagerDemandDataView,
    ConsumerGeneratorAllocationApproveView,
    ConsumerGeneratorAllocationRevokeView,
    ConsumerGeneratorAllocationGenerateView,
    ConsumerGeneratorAllocationRecommendationsView,
    ConsumerAllocationSlotsView,
    ConsumerManagerGeneratorSupplyUploadRevisionResolveView,
    ConsumerManagerGeneratorSupplyUploadRevisionsPendingView,
    DemandEntryView,
    GeneratorConsumerDemandSlotsView,
    GeneratorDummySupplySlotsView,
    GeneratorConsumerManagersView,
    GeneratorApprovedAllocationSlotsView,
    PlantApprovedAllocationSlotsView,
    GeneratorSupplyScheduleView,
    GeneratorDashboardKaiView,
    PlantDashboardKaiView,
    ConsumerManagerDashboardKpiView,
    ConsumerManagerDashboardKaiView,
    ConsumerManagerReportsPlantSlotsView,
    PlantDashboardView,
    PlantDashboardWeekView,
    PlantDashboardSlotsView,
    IexGreenDayAheadMcpView,
    IexPredictionCompareView,
    IexScrapedPredictionView,
    ReportsSummaryView,
    SlotApproveView,
    SlotApproveBulkView,
    SlotRevokeView,
    SlotOverrideApproveView,
)

app_name = 'allocation_api'

urlpatterns = [
    path('demand-entry/', DemandEntryView.as_view(), name='demand_entry'),
    path('dashboard/', PlantDashboardView.as_view(), name='plant_dashboard'),
    path('plant/dashboard-kai/', PlantDashboardKaiView.as_view(), name='plant_dashboard_kai'),
    path('dashboard/week/', PlantDashboardWeekView.as_view(), name='plant_dashboard_week'),
    path('dashboard/slots/', PlantDashboardSlotsView.as_view(), name='plant_dashboard_slots'),
    path('consumer-demand-entry/', ConsumerManagerDemandEntrySummaryView.as_view(), name='consumer_demand_entry'),
    path('consumer-demand-entry/plant-slots/', ConsumerManagerPlantDemandSlotsView.as_view(), name='consumer_demand_entry_plant_slots'),
    path('consumer-demand-entry/overall-slots/', ConsumerManagerOverallDemandSlotsView.as_view(), name='consumer_demand_entry_overall_slots'),
    path('consumer-demand-approve/', ConsumerManagerApproveDemandView.as_view(), name='consumer_demand_approve'),
    path('consumer-demand-entry/approve-generator-schedule/', ConsumerManagerApproveGeneratorScheduleView.as_view(), name='consumer_approve_generator_schedule'),
    path('consumer-demand/week/', ConsumerManagerDemandWeekView.as_view(), name='consumer_demand_week'),
    path('demand-data/', ConsumerManagerDemandDataView.as_view(), name='demand_data'),
    path('consumer-manager/dashboard-kpis/', ConsumerManagerDashboardKpiView.as_view(), name='consumer_manager_dashboard_kpis'),
    path('consumer-manager/dashboard-kai/', ConsumerManagerDashboardKaiView.as_view(), name='consumer_manager_dashboard_kai'),
    path('consumer-manager/reports/plant-slots/', ConsumerManagerReportsPlantSlotsView.as_view(), name='consumer_manager_reports_plant_slots'),
    path('consumer-generator-allocations/generate/', ConsumerGeneratorAllocationGenerateView.as_view(), name='consumer_generator_allocations_generate'),
    path('consumer-generator-allocations/recommendations/', ConsumerGeneratorAllocationRecommendationsView.as_view(), name='consumer_generator_allocations_recommendations'),
    path('consumer-generator-allocations/approve/', ConsumerGeneratorAllocationApproveView.as_view(), name='consumer_generator_allocations_approve'),
    path('consumer-generator-allocations/revoke/', ConsumerGeneratorAllocationRevokeView.as_view(), name='consumer_generator_allocations_revoke'),
    path('slot-approve/', SlotApproveView.as_view(), name='slot_approve'),
    path('slot-approve-bulk/', SlotApproveBulkView.as_view(), name='slot_approve_bulk'),
    path('slot-revoke/', SlotRevokeView.as_view(), name='slot_revoke'),
    path('slot-override-approve/', SlotOverrideApproveView.as_view(), name='slot_override_approve'),
    path('iex/green-day-ahead/mcp/', IexGreenDayAheadMcpView.as_view(), name='iex_green_day_ahead_mcp'),
    path('iex/prediction-compare/', IexPredictionCompareView.as_view(), name='iex_prediction_compare'),
    path('iex-scraped-predictions/', IexScrapedPredictionView.as_view(), name='iex_scraped_predictions'),
    path('generator/consumer-managers/', GeneratorConsumerManagersView.as_view(), name='generator_consumer_managers'),
    path('generator/consumer-demand-slots/', GeneratorConsumerDemandSlotsView.as_view(), name='generator_consumer_demand_slots'),
    path('generator/dummy-supply-slots/', GeneratorDummySupplySlotsView.as_view(), name='generator_dummy_supply_slots'),
    path('generator/approved-allocation-slots/', GeneratorApprovedAllocationSlotsView.as_view(), name='generator_approved_allocation_slots'),
    path('plant/approved-allocation-slots/', PlantApprovedAllocationSlotsView.as_view(), name='plant_approved_allocation_slots'),
    path('generator/supply/', GeneratorSupplyScheduleView.as_view(), name='generator_supply'),
    path('generator/dashboard-kai/', GeneratorDashboardKaiView.as_view(), name='generator_dashboard_kai'),
    path('consumer-allocation/', ConsumerAllocationSlotsView.as_view(), name='consumer_allocation'),
    path(
        'consumer-manager/generator-upload-revisions/pending/',
        ConsumerManagerGeneratorSupplyUploadRevisionsPendingView.as_view(),
        name='consumer_manager_generator_upload_revisions_pending',
    ),
    path(
        'consumer-manager/generator-upload-revisions/resolve/',
        ConsumerManagerGeneratorSupplyUploadRevisionResolveView.as_view(),
        name='consumer_manager_generator_upload_revision_resolve',
    ),
    path('reports/summary/', ReportsSummaryView.as_view(), name='reports_summary'),
]

