# Generated by Django 5.2.12 on 2026-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='grid_tariff_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='plant',
            name='re_tariff_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
