# Generated by Django 5.2.12 on 2026-03-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plant_grid_tariff_per_unit_plant_re_tariff_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttransmissionloss',
            name='central_transmission_loss_percent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='planttransmissionloss',
            name='state_transition_loss_percent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
