# Generated by Django 5.2.12 on 2026-03-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_planttransmissionloss_central_transmission_loss_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='hourly_tariff_difference',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
