from django.urls import path
from django.views.generic import RedirectView

from .views import (
    consumer_manager_dashboard_page,
    consumer_manager_demand_entry_page,
    demand_entry_page,
    demand_entry_list_page,
    login_page,
    dashboard_page,
    platform_admin_dashboard_page,
    plant_user_dashboard_page,
    plant_user_allocations_page,
    demand_entry_schedule_page,
    generator_allocation_page,
    generator_dashboard_page,
    generator_demand_page,
    consumer_allocation_page,
    consumer_plantwise_allocation_page,
    generator_allocation_edit_page,
    generator_schedule_revisions_page,
    plant_management_page,
    iex_predictor_page,
    reports_page,
    settings_view,
    generator_settings_page,
    logout_view,
)

urlpatterns = [
    path('', login_page, name='root_login'),
    path('login/', login_page, name='login'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', dashboard_page, name='dashboard'),
    path('demand-entry/', demand_entry_list_page, name='demand_entry'),
    path('demand-entry/day/<slug:date_str>/', demand_entry_schedule_page, name='demand_entry_schedule'),
    path('platform-admin-dashboard/', platform_admin_dashboard_page, name='platform_admin_dashboard'),
    path('consumer-manager-dashboard/', consumer_manager_dashboard_page, name='consumer_manager_dashboard'),
    path('consumer-demand-entry/', consumer_manager_demand_entry_page, name='consumer_demand_entry'),
    path('plant-user-dashboard/', plant_user_dashboard_page, name='plant_user_dashboard'),
    path('plant-allocations/', plant_user_allocations_page, name='plant_user_allocations'),
    path('generator-dashboard/', generator_dashboard_page, name='generator_dashboard'),
    path(
        'generator-dashboard-1/',
        RedirectView.as_view(pattern_name='generator_dashboard', permanent=False),
    ),
    path('generator-demand/', generator_demand_page, name='generator_demand'),
    path('generator-allocation/', generator_allocation_page, name='generator_allocation'),
    path('generator-schedule-revisions/', generator_schedule_revisions_page, name='generator_schedule_revisions'),
    path('generator-allocation/edit/<int:consumer_manager_user_id>/<slug:date_str>/', generator_allocation_edit_page, name='generator_allocation_edit'),
    path('consumer-allocation/', consumer_allocation_page, name='consumer_allocation'),
    path('consumer-plantwise-allocation/', consumer_plantwise_allocation_page, name='consumer_plantwise_allocation'),
    path('plant-management/', plant_management_page, name='plant_management'),
    path('iex-predictor/', iex_predictor_page, name='iex_predictor'),
    path('reports/', reports_page, name='reports'),
    path('settings/', settings_view, name='settings'),
    path('generator-settings/', generator_settings_page, name='generator_settings'),
]

