# Generated by Django 5.2.12 on 2026-03-20 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shutdown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_schedules_created', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_schedules', to='core.plant')),
            ],
        ),
        migrations.CreateModel(
            name='DemandSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveIntegerField()),
                ('slot_time', models.TimeField()),
                ('demand_mw', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='allocation.demandschedule')),
            ],
            options={
                'ordering': ['slot_index'],
            },
        ),
        migrations.AddIndex(
            model_name='demandschedule',
            index=models.Index(fields=['plant', 'date'], name='allocation__plant_i_20cb00_idx'),
        ),
        migrations.AddConstraint(
            model_name='demandschedule',
            constraint=models.UniqueConstraint(fields=('plant', 'date'), name='unique_plant_date_schedule'),
        ),
        migrations.AddConstraint(
            model_name='demandslot',
            constraint=models.UniqueConstraint(fields=('schedule', 'slot_index'), name='unique_schedule_slot_index'),
        ),
    ]
