# Generated by Django 5.2.12 on 2026-03-20 08:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_consumerdemandapproval'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorSupplySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator_supply_schedules', to='core.consumer')),
                ('submitted_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generator_supply_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorSupplySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveIntegerField()),
                ('slot_time', models.TimeField()),
                ('supply_mwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='allocation.generatorsupplyschedule')),
            ],
            options={
                'ordering': ['slot_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='generatorsupplyschedule',
            constraint=models.UniqueConstraint(fields=('consumer', 'date'), name='unique_generator_supply_consumer_date'),
        ),
        migrations.AddConstraint(
            model_name='generatorsupplyslot',
            constraint=models.UniqueConstraint(fields=('schedule', 'slot_index'), name='unique_generator_supply_slot_index'),
        ),
    ]
