# Generated by Django 5.2.12 on 2026-03-20 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_generatorsupplyschedule_generatorsupplyslot_and_more'),
        ('core', '0002_plant_grid_tariff_per_unit_plant_re_tariff_per_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerGeneratorAllocationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved')], default='SUGGESTED', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_runs', to='core.consumer')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_runs_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerGeneratorAllocationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('AI_TOTAL', 'Ai Total')], default='AI_TOTAL', max_length=16)),
                ('ai_alloc_mwh_override_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_overrides', to='core.plant')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_overrides', to='allocation.consumergeneratorallocationrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='consumergeneratorallocationrun',
            constraint=models.UniqueConstraint(fields=('consumer', 'date'), name='unique_consumer_allocation_run_date'),
        ),
        migrations.AddConstraint(
            model_name='consumergeneratorallocationoverride',
            constraint=models.UniqueConstraint(fields=('run', 'plant'), name='unique_run_plant_ai_override'),
        ),
    ]
