# Generated by Django 5.2.12 on 2026-03-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_consumergeneratorallocationrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IexGreenDayAheadMcpSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_index', models.PositiveIntegerField()),
                ('slot_time', models.TimeField()),
                ('mcp_rs_per_mwh', models.DecimalField(decimal_places=4, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='allocation__date_03de66_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'slot_index'), name='unique_iex_mcp_date_slot_index')],
            },
        ),
    ]
