# Generated by Django 5.2.12 on 2026-03-21 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_iexgreendayaheadmcpslot'),
        ('core', '0004_add_hourly_tariff_difference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorScheduleApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generator_schedule_approvals_created', to=settings.AUTH_USER_MODEL)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator_schedule_approvals', to='core.consumer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('consumer', 'date'), name='unique_consumer_date_generator_schedule_approval')],
            },
        ),
    ]
