# Generated by Django 5.2.12 on 2026-05-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0009_slotallocationapproval_revision3'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='slotallocationapproval',
            new_name='allocation__consume_ed6623_idx',
            old_name='allocation_s_consumer_2b5c0e_idx',
        ),
    ]
