# Generated by Django 5.2.12 on 2026-05-12 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0010_rename_allocation_s_consumer_2b5c0e_idx_allocation__consume_ed6623_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorSupplyUploadRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generator_supply_upload_revisions', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_revisions', to='allocation.generatorsupplyschedule')),
            ],
            options={
                'ordering': ['revision_number'],
            },
        ),
        migrations.CreateModel(
            name='GeneratorSupplyUploadRevisionDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveIntegerField()),
                ('previous_mwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('new_mwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas', to='allocation.generatorsupplyuploadrevision')),
            ],
            options={
                'ordering': ['slot_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='generatorsupplyuploadrevision',
            constraint=models.UniqueConstraint(fields=('schedule', 'revision_number'), name='unique_generator_supply_upload_rev_no'),
        ),
        migrations.AddConstraint(
            model_name='generatorsupplyuploadrevisiondelta',
            constraint=models.UniqueConstraint(fields=('revision', 'slot_index'), name='unique_upload_revision_delta_slot'),
        ),
    ]
